# Generated by Django 2.2 on 2022-07-03 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_snippet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='text',
            field=models.TextField(default='Hello World'),
        ),
    ]
