# Generated by Django 2.2 on 2022-07-03 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20220703_1703'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Snippet',
        ),
    ]
