# Generated by Django 2.2 on 2022-07-03 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_snippet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='id',
        ),
        migrations.AddField(
            model_name='solution',
            name='code',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='solution',
            name='solution_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
