# Generated by Django 2.2 on 2022-07-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20220704_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='solution_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
