# Generated by Django 2.2 on 2022-07-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220704_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='solution_id',
        ),
        migrations.AddField(
            model_name='solution',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
